owner: GracePeterMutiibwa
repo: clearnique-status-
sites:
  - name: Clearnique Chat
    url: https://chat.clearnique.com
  - name: Clearnique Home
    url: https://clearnique.com
  - name: Cingest API
    url: https://ingest.clearnique.com
status-website:
  cname: status.clearnique.com
  name: Clearnique Status
  introTitle: Clearnique Service Status
  introMessage: Real-time status for all Clearnique services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/GracePeterMutiibwa/clearnique-status-
