owner: GracePeterMutiibwa
repo: clearnique-status-
sites:
  - name: Clearnique Chat
    url: https://chat.clearnique.com
  - name: Clearnique Home
    url: https://clearnique.com
  - name: Cingest API
    url: https://ingest.clearnique.com
status-website:
  cname: status.clearnique.com
  name: Are we Online?
  introTitle: Clearnique Service Status
  introMessage: Real-time status for all Clearnique services.
  logoUrl: https://clearnique.com/served/nh/ingray.svg
  favIconUrl: https://clearnique.com/served/images/clns.svg
  navbar:
    - title: Status
      href: /
    - title: Get Started
      href: https://clearnique.com
